# pull the Node.js Docker image
FROM node:alpine

# create the directory inside the container
WORKDIR /usr/src/app

RUN mkdir js
# copy the package.json files from local machine to the workdir in container
COPY ./js/package*.json ./js

# run npm install in our local machine

RUN cd js && npm install && npm i -S pdf-to-base64 && npm install web3 && npm install solc@0.8.0


# copy the generated modules and all other files to the container
COPY . . 

# our app is running on port 5000 within the container, so need to expose it
EXPOSE 5000
EXPOSE 8545
EXPOSE 9200

# the command that starts our app
CMD ["node", "./js/index.js"]
